name: Update README

on:
  schedule:
    - cron: '30 0 * * *'  # daily at 6:00 AM IST
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Last Updated Date
        run: |
          DATE=$(TZ="Asia/Kolkata" date '+%Y-%m-%d %H:%M:%S')
          # Remove any trailing carriage returns (for Windows line endings)
          tr -d '\r' < README.md > README.tmp && mv README.tmp README.md
          # Replace <!--DATE--> (even if extra spaces) or append if not found
          if grep -q '<!--DATE-->' README.md; then
            sed -i "s/<!--DATE-->/$DATE/" README.md
          else
            echo -e "\nLast Updated: $DATE" >> README.md
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update README with latest date" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/T-Stephen/T-Stephen.git
