name: Update README

# Allows manual trigger
on:
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Update README (example: insert latest date)
    - name: Update README
      run: |
        DATE=$(date '+%Y-%m-%d %H:%M:%S')
        echo "Last updated: $DATE" > README.md

    # Step 3: Commit and push changes
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "chore: update README with latest date" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/T-Stephen/T-Stephen.git
